// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(pika_coreFFI)
import pika_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pika_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pika_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePikaCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol FfiAppProtocol: AnyObject, Sendable {
    
    func dispatch(action: AppAction) 
    
    func listenForUpdates(reconciler: AppReconciler) 
    
    func state()  -> AppState
    
}
open class FfiApp: FfiAppProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_pika_core_fn_clone_ffiapp(self.handle, $0) }
    }
public convenience init(dataDir: String) {
    let handle =
        try! rustCall() {
    uniffi_pika_core_fn_constructor_ffiapp_new(
        FfiConverterString.lower(dataDir),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_pika_core_fn_free_ffiapp(handle, $0) }
    }

    

    
open func dispatch(action: AppAction)  {try! rustCall() {
    uniffi_pika_core_fn_method_ffiapp_dispatch(
            self.uniffiCloneHandle(),
        FfiConverterTypeAppAction_lower(action),$0
    )
}
}
    
open func listenForUpdates(reconciler: AppReconciler)  {try! rustCall() {
    uniffi_pika_core_fn_method_ffiapp_listen_for_updates(
            self.uniffiCloneHandle(),
        FfiConverterCallbackInterfaceAppReconciler_lower(reconciler),$0
    )
}
}
    
open func state() -> AppState  {
    return try!  FfiConverterTypeAppState_lift(try! rustCall() {
    uniffi_pika_core_fn_method_ffiapp_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiApp: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiApp

    public static func lift(_ handle: UInt64) throws -> FfiApp {
        return FfiApp(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiApp) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiApp {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiApp, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiApp_lift(_ handle: UInt64) throws -> FfiApp {
    return try FfiConverterTypeFfiApp.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiApp_lower(_ value: FfiApp) -> UInt64 {
    return FfiConverterTypeFfiApp.lower(value)
}




public struct AppState: Equatable, Hashable {
    public var rev: UInt64
    public var router: Router
    public var auth: AuthState
    public var myProfile: MyProfileState
    public var busy: BusyState
    public var chatList: [ChatSummary]
    public var currentChat: ChatViewState?
    public var followList: [FollowListEntry]
    public var peerProfile: PeerProfileState?
    public var toast: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rev: UInt64, router: Router, auth: AuthState, myProfile: MyProfileState, busy: BusyState, chatList: [ChatSummary], currentChat: ChatViewState?, followList: [FollowListEntry], peerProfile: PeerProfileState?, toast: String?) {
        self.rev = rev
        self.router = router
        self.auth = auth
        self.myProfile = myProfile
        self.busy = busy
        self.chatList = chatList
        self.currentChat = currentChat
        self.followList = followList
        self.peerProfile = peerProfile
        self.toast = toast
    }

    

    
}

#if compiler(>=6)
extension AppState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppState {
        return
            try AppState(
                rev: FfiConverterUInt64.read(from: &buf), 
                router: FfiConverterTypeRouter.read(from: &buf), 
                auth: FfiConverterTypeAuthState.read(from: &buf), 
                myProfile: FfiConverterTypeMyProfileState.read(from: &buf), 
                busy: FfiConverterTypeBusyState.read(from: &buf), 
                chatList: FfiConverterSequenceTypeChatSummary.read(from: &buf), 
                currentChat: FfiConverterOptionTypeChatViewState.read(from: &buf), 
                followList: FfiConverterSequenceTypeFollowListEntry.read(from: &buf), 
                peerProfile: FfiConverterOptionTypePeerProfileState.read(from: &buf), 
                toast: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: AppState, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.rev, into: &buf)
        FfiConverterTypeRouter.write(value.router, into: &buf)
        FfiConverterTypeAuthState.write(value.auth, into: &buf)
        FfiConverterTypeMyProfileState.write(value.myProfile, into: &buf)
        FfiConverterTypeBusyState.write(value.busy, into: &buf)
        FfiConverterSequenceTypeChatSummary.write(value.chatList, into: &buf)
        FfiConverterOptionTypeChatViewState.write(value.currentChat, into: &buf)
        FfiConverterSequenceTypeFollowListEntry.write(value.followList, into: &buf)
        FfiConverterOptionTypePeerProfileState.write(value.peerProfile, into: &buf)
        FfiConverterOptionString.write(value.toast, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppState_lift(_ buf: RustBuffer) throws -> AppState {
    return try FfiConverterTypeAppState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppState_lower(_ value: AppState) -> RustBuffer {
    return FfiConverterTypeAppState.lower(value)
}


public struct BusyState: Equatable, Hashable {
    public var creatingAccount: Bool
    public var loggingIn: Bool
    public var creatingChat: Bool
    public var fetchingFollowList: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(creatingAccount: Bool, loggingIn: Bool, creatingChat: Bool, fetchingFollowList: Bool) {
        self.creatingAccount = creatingAccount
        self.loggingIn = loggingIn
        self.creatingChat = creatingChat
        self.fetchingFollowList = fetchingFollowList
    }

    

    
}

#if compiler(>=6)
extension BusyState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBusyState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BusyState {
        return
            try BusyState(
                creatingAccount: FfiConverterBool.read(from: &buf), 
                loggingIn: FfiConverterBool.read(from: &buf), 
                creatingChat: FfiConverterBool.read(from: &buf), 
                fetchingFollowList: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: BusyState, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.creatingAccount, into: &buf)
        FfiConverterBool.write(value.loggingIn, into: &buf)
        FfiConverterBool.write(value.creatingChat, into: &buf)
        FfiConverterBool.write(value.fetchingFollowList, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBusyState_lift(_ buf: RustBuffer) throws -> BusyState {
    return try FfiConverterTypeBusyState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBusyState_lower(_ value: BusyState) -> RustBuffer {
    return FfiConverterTypeBusyState.lower(value)
}


public struct ChatMessage: Equatable, Hashable {
    public var id: String
    public var senderPubkey: String
    public var senderName: String?
    public var content: String
    public var displayContent: String
    public var mentions: [Mention]
    public var timestamp: Int64
    public var isMine: Bool
    public var delivery: MessageDeliveryState
    public var pollTally: [PollTally]
    public var myPollVote: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, senderPubkey: String, senderName: String?, content: String, displayContent: String, mentions: [Mention], timestamp: Int64, isMine: Bool, delivery: MessageDeliveryState, pollTally: [PollTally], myPollVote: String?) {
        self.id = id
        self.senderPubkey = senderPubkey
        self.senderName = senderName
        self.content = content
        self.displayContent = displayContent
        self.mentions = mentions
        self.timestamp = timestamp
        self.isMine = isMine
        self.delivery = delivery
        self.pollTally = pollTally
        self.myPollVote = myPollVote
    }

    

    
}

#if compiler(>=6)
extension ChatMessage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChatMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatMessage {
        return
            try ChatMessage(
                id: FfiConverterString.read(from: &buf), 
                senderPubkey: FfiConverterString.read(from: &buf), 
                senderName: FfiConverterOptionString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                displayContent: FfiConverterString.read(from: &buf), 
                mentions: FfiConverterSequenceTypeMention.read(from: &buf), 
                timestamp: FfiConverterInt64.read(from: &buf), 
                isMine: FfiConverterBool.read(from: &buf), 
                delivery: FfiConverterTypeMessageDeliveryState.read(from: &buf), 
                pollTally: FfiConverterSequenceTypePollTally.read(from: &buf), 
                myPollVote: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ChatMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.senderPubkey, into: &buf)
        FfiConverterOptionString.write(value.senderName, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterString.write(value.displayContent, into: &buf)
        FfiConverterSequenceTypeMention.write(value.mentions, into: &buf)
        FfiConverterInt64.write(value.timestamp, into: &buf)
        FfiConverterBool.write(value.isMine, into: &buf)
        FfiConverterTypeMessageDeliveryState.write(value.delivery, into: &buf)
        FfiConverterSequenceTypePollTally.write(value.pollTally, into: &buf)
        FfiConverterOptionString.write(value.myPollVote, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatMessage_lift(_ buf: RustBuffer) throws -> ChatMessage {
    return try FfiConverterTypeChatMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatMessage_lower(_ value: ChatMessage) -> RustBuffer {
    return FfiConverterTypeChatMessage.lower(value)
}


public struct ChatSummary: Equatable, Hashable {
    public var chatId: String
    public var isGroup: Bool
    public var groupName: String?
    public var members: [MemberInfo]
    public var lastMessage: String?
    public var lastMessageAt: Int64?
    public var unreadCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chatId: String, isGroup: Bool, groupName: String?, members: [MemberInfo], lastMessage: String?, lastMessageAt: Int64?, unreadCount: UInt32) {
        self.chatId = chatId
        self.isGroup = isGroup
        self.groupName = groupName
        self.members = members
        self.lastMessage = lastMessage
        self.lastMessageAt = lastMessageAt
        self.unreadCount = unreadCount
    }

    

    
}

#if compiler(>=6)
extension ChatSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChatSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatSummary {
        return
            try ChatSummary(
                chatId: FfiConverterString.read(from: &buf), 
                isGroup: FfiConverterBool.read(from: &buf), 
                groupName: FfiConverterOptionString.read(from: &buf), 
                members: FfiConverterSequenceTypeMemberInfo.read(from: &buf), 
                lastMessage: FfiConverterOptionString.read(from: &buf), 
                lastMessageAt: FfiConverterOptionInt64.read(from: &buf), 
                unreadCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ChatSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.chatId, into: &buf)
        FfiConverterBool.write(value.isGroup, into: &buf)
        FfiConverterOptionString.write(value.groupName, into: &buf)
        FfiConverterSequenceTypeMemberInfo.write(value.members, into: &buf)
        FfiConverterOptionString.write(value.lastMessage, into: &buf)
        FfiConverterOptionInt64.write(value.lastMessageAt, into: &buf)
        FfiConverterUInt32.write(value.unreadCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatSummary_lift(_ buf: RustBuffer) throws -> ChatSummary {
    return try FfiConverterTypeChatSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatSummary_lower(_ value: ChatSummary) -> RustBuffer {
    return FfiConverterTypeChatSummary.lower(value)
}


public struct ChatViewState: Equatable, Hashable {
    public var chatId: String
    public var isGroup: Bool
    public var groupName: String?
    public var members: [MemberInfo]
    public var isAdmin: Bool
    public var messages: [ChatMessage]
    public var canLoadOlder: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chatId: String, isGroup: Bool, groupName: String?, members: [MemberInfo], isAdmin: Bool, messages: [ChatMessage], canLoadOlder: Bool) {
        self.chatId = chatId
        self.isGroup = isGroup
        self.groupName = groupName
        self.members = members
        self.isAdmin = isAdmin
        self.messages = messages
        self.canLoadOlder = canLoadOlder
    }

    

    
}

#if compiler(>=6)
extension ChatViewState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChatViewState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatViewState {
        return
            try ChatViewState(
                chatId: FfiConverterString.read(from: &buf), 
                isGroup: FfiConverterBool.read(from: &buf), 
                groupName: FfiConverterOptionString.read(from: &buf), 
                members: FfiConverterSequenceTypeMemberInfo.read(from: &buf), 
                isAdmin: FfiConverterBool.read(from: &buf), 
                messages: FfiConverterSequenceTypeChatMessage.read(from: &buf), 
                canLoadOlder: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ChatViewState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.chatId, into: &buf)
        FfiConverterBool.write(value.isGroup, into: &buf)
        FfiConverterOptionString.write(value.groupName, into: &buf)
        FfiConverterSequenceTypeMemberInfo.write(value.members, into: &buf)
        FfiConverterBool.write(value.isAdmin, into: &buf)
        FfiConverterSequenceTypeChatMessage.write(value.messages, into: &buf)
        FfiConverterBool.write(value.canLoadOlder, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatViewState_lift(_ buf: RustBuffer) throws -> ChatViewState {
    return try FfiConverterTypeChatViewState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatViewState_lower(_ value: ChatViewState) -> RustBuffer {
    return FfiConverterTypeChatViewState.lower(value)
}


public struct FollowListEntry: Equatable, Hashable {
    public var pubkey: String
    public var npub: String
    public var name: String?
    public var pictureUrl: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pubkey: String, npub: String, name: String?, pictureUrl: String?) {
        self.pubkey = pubkey
        self.npub = npub
        self.name = name
        self.pictureUrl = pictureUrl
    }

    

    
}

#if compiler(>=6)
extension FollowListEntry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFollowListEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FollowListEntry {
        return
            try FollowListEntry(
                pubkey: FfiConverterString.read(from: &buf), 
                npub: FfiConverterString.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                pictureUrl: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FollowListEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterString.write(value.npub, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.pictureUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFollowListEntry_lift(_ buf: RustBuffer) throws -> FollowListEntry {
    return try FfiConverterTypeFollowListEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFollowListEntry_lower(_ value: FollowListEntry) -> RustBuffer {
    return FfiConverterTypeFollowListEntry.lower(value)
}


public struct MemberInfo: Equatable, Hashable {
    public var pubkey: String
    public var npub: String
    public var name: String?
    public var pictureUrl: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pubkey: String, npub: String, name: String?, pictureUrl: String?) {
        self.pubkey = pubkey
        self.npub = npub
        self.name = name
        self.pictureUrl = pictureUrl
    }

    

    
}

#if compiler(>=6)
extension MemberInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMemberInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MemberInfo {
        return
            try MemberInfo(
                pubkey: FfiConverterString.read(from: &buf), 
                npub: FfiConverterString.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                pictureUrl: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: MemberInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterString.write(value.npub, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.pictureUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemberInfo_lift(_ buf: RustBuffer) throws -> MemberInfo {
    return try FfiConverterTypeMemberInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemberInfo_lower(_ value: MemberInfo) -> RustBuffer {
    return FfiConverterTypeMemberInfo.lower(value)
}


public struct Mention: Equatable, Hashable {
    public var npub: String
    public var displayName: String
    public var start: UInt32
    public var end: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(npub: String, displayName: String, start: UInt32, end: UInt32) {
        self.npub = npub
        self.displayName = displayName
        self.start = start
        self.end = end
    }

    

    
}

#if compiler(>=6)
extension Mention: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMention: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Mention {
        return
            try Mention(
                npub: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                start: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: Mention, into buf: inout [UInt8]) {
        FfiConverterString.write(value.npub, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMention_lift(_ buf: RustBuffer) throws -> Mention {
    return try FfiConverterTypeMention.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMention_lower(_ value: Mention) -> RustBuffer {
    return FfiConverterTypeMention.lower(value)
}


public struct MyProfileState: Equatable, Hashable {
    public var name: String
    public var about: String
    public var pictureUrl: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, about: String, pictureUrl: String?) {
        self.name = name
        self.about = about
        self.pictureUrl = pictureUrl
    }

    

    
}

#if compiler(>=6)
extension MyProfileState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMyProfileState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MyProfileState {
        return
            try MyProfileState(
                name: FfiConverterString.read(from: &buf), 
                about: FfiConverterString.read(from: &buf), 
                pictureUrl: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: MyProfileState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.about, into: &buf)
        FfiConverterOptionString.write(value.pictureUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMyProfileState_lift(_ buf: RustBuffer) throws -> MyProfileState {
    return try FfiConverterTypeMyProfileState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMyProfileState_lower(_ value: MyProfileState) -> RustBuffer {
    return FfiConverterTypeMyProfileState.lower(value)
}


public struct PeerProfileState: Equatable, Hashable {
    public var pubkey: String
    public var npub: String
    public var name: String?
    public var about: String?
    public var pictureUrl: String?
    public var isFollowed: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pubkey: String, npub: String, name: String?, about: String?, pictureUrl: String?, isFollowed: Bool) {
        self.pubkey = pubkey
        self.npub = npub
        self.name = name
        self.about = about
        self.pictureUrl = pictureUrl
        self.isFollowed = isFollowed
    }

    

    
}

#if compiler(>=6)
extension PeerProfileState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePeerProfileState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PeerProfileState {
        return
            try PeerProfileState(
                pubkey: FfiConverterString.read(from: &buf), 
                npub: FfiConverterString.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                about: FfiConverterOptionString.read(from: &buf), 
                pictureUrl: FfiConverterOptionString.read(from: &buf), 
                isFollowed: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PeerProfileState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterString.write(value.npub, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.about, into: &buf)
        FfiConverterOptionString.write(value.pictureUrl, into: &buf)
        FfiConverterBool.write(value.isFollowed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePeerProfileState_lift(_ buf: RustBuffer) throws -> PeerProfileState {
    return try FfiConverterTypePeerProfileState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePeerProfileState_lower(_ value: PeerProfileState) -> RustBuffer {
    return FfiConverterTypePeerProfileState.lower(value)
}


public struct PollTally: Equatable, Hashable {
    public var option: String
    public var count: UInt32
    public var voterNames: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(option: String, count: UInt32, voterNames: [String]) {
        self.option = option
        self.count = count
        self.voterNames = voterNames
    }

    

    
}

#if compiler(>=6)
extension PollTally: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePollTally: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PollTally {
        return
            try PollTally(
                option: FfiConverterString.read(from: &buf), 
                count: FfiConverterUInt32.read(from: &buf), 
                voterNames: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: PollTally, into buf: inout [UInt8]) {
        FfiConverterString.write(value.option, into: &buf)
        FfiConverterUInt32.write(value.count, into: &buf)
        FfiConverterSequenceString.write(value.voterNames, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePollTally_lift(_ buf: RustBuffer) throws -> PollTally {
    return try FfiConverterTypePollTally.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePollTally_lower(_ value: PollTally) -> RustBuffer {
    return FfiConverterTypePollTally.lower(value)
}


public struct Router: Equatable, Hashable {
    public var defaultScreen: Screen
    public var screenStack: [Screen]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(defaultScreen: Screen, screenStack: [Screen]) {
        self.defaultScreen = defaultScreen
        self.screenStack = screenStack
    }

    

    
}

#if compiler(>=6)
extension Router: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRouter: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Router {
        return
            try Router(
                defaultScreen: FfiConverterTypeScreen.read(from: &buf), 
                screenStack: FfiConverterSequenceTypeScreen.read(from: &buf)
        )
    }

    public static func write(_ value: Router, into buf: inout [UInt8]) {
        FfiConverterTypeScreen.write(value.defaultScreen, into: &buf)
        FfiConverterSequenceTypeScreen.write(value.screenStack, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRouter_lift(_ buf: RustBuffer) throws -> Router {
    return try FfiConverterTypeRouter.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRouter_lower(_ value: Router) -> RustBuffer {
    return FfiConverterTypeRouter.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AppAction: Equatable, Hashable {
    
    case createAccount
    case login(nsec: String
    )
    case restoreSession(nsec: String
    )
    case logout
    case refreshMyProfile
    case saveMyProfile(name: String, about: String
    )
    case uploadMyProfileImage(imageBase64: String, mimeType: String
    )
    case pushScreen(screen: Screen
    )
    case updateScreenStack(stack: [Screen]
    )
    case createChat(peerNpub: String
    )
    case sendMessage(chatId: String, content: String
    )
    case retryMessage(chatId: String, messageId: String
    )
    case openChat(chatId: String
    )
    case loadOlderMessages(chatId: String, beforeMessageId: String, limit: UInt32
    )
    case createGroupChat(peerNpubs: [String], groupName: String
    )
    case addGroupMembers(chatId: String, peerNpubs: [String]
    )
    case removeGroupMembers(chatId: String, memberPubkeys: [String]
    )
    case leaveGroup(chatId: String
    )
    case renameGroup(chatId: String, name: String
    )
    case archiveChat(chatId: String
    )
    case clearToast
    case foregrounded
    case openPeerProfile(pubkey: String
    )
    case closePeerProfile
    case refreshFollowList
    case followUser(pubkey: String
    )
    case unfollowUser(pubkey: String
    )





}

#if compiler(>=6)
extension AppAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppAction: FfiConverterRustBuffer {
    typealias SwiftType = AppAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .createAccount
        
        case 2: return .login(nsec: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .restoreSession(nsec: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .logout
        
        case 5: return .refreshMyProfile
        
        case 6: return .saveMyProfile(name: try FfiConverterString.read(from: &buf), about: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .uploadMyProfileImage(imageBase64: try FfiConverterString.read(from: &buf), mimeType: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .pushScreen(screen: try FfiConverterTypeScreen.read(from: &buf)
        )
        
        case 9: return .updateScreenStack(stack: try FfiConverterSequenceTypeScreen.read(from: &buf)
        )
        
        case 10: return .createChat(peerNpub: try FfiConverterString.read(from: &buf)
        )
        
        case 11: return .sendMessage(chatId: try FfiConverterString.read(from: &buf), content: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .retryMessage(chatId: try FfiConverterString.read(from: &buf), messageId: try FfiConverterString.read(from: &buf)
        )
        
        case 13: return .openChat(chatId: try FfiConverterString.read(from: &buf)
        )
        
        case 14: return .loadOlderMessages(chatId: try FfiConverterString.read(from: &buf), beforeMessageId: try FfiConverterString.read(from: &buf), limit: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 15: return .createGroupChat(peerNpubs: try FfiConverterSequenceString.read(from: &buf), groupName: try FfiConverterString.read(from: &buf)
        )
        
        case 16: return .addGroupMembers(chatId: try FfiConverterString.read(from: &buf), peerNpubs: try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 17: return .removeGroupMembers(chatId: try FfiConverterString.read(from: &buf), memberPubkeys: try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 18: return .leaveGroup(chatId: try FfiConverterString.read(from: &buf)
        )
        
        case 19: return .renameGroup(chatId: try FfiConverterString.read(from: &buf), name: try FfiConverterString.read(from: &buf)
        )
        
        case 20: return .archiveChat(chatId: try FfiConverterString.read(from: &buf)
        )
        
        case 21: return .clearToast
        
        case 22: return .foregrounded
        
        case 23: return .openPeerProfile(pubkey: try FfiConverterString.read(from: &buf)
        )
        
        case 24: return .closePeerProfile
        
        case 25: return .refreshFollowList
        
        case 26: return .followUser(pubkey: try FfiConverterString.read(from: &buf)
        )
        
        case 27: return .unfollowUser(pubkey: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AppAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .createAccount:
            writeInt(&buf, Int32(1))
        
        
        case let .login(nsec):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(nsec, into: &buf)
            
        
        case let .restoreSession(nsec):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(nsec, into: &buf)
            
        
        case .logout:
            writeInt(&buf, Int32(4))
        
        
        case .refreshMyProfile:
            writeInt(&buf, Int32(5))
        
        
        case let .saveMyProfile(name,about):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(about, into: &buf)
            
        
        case let .uploadMyProfileImage(imageBase64,mimeType):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(imageBase64, into: &buf)
            FfiConverterString.write(mimeType, into: &buf)
            
        
        case let .pushScreen(screen):
            writeInt(&buf, Int32(8))
            FfiConverterTypeScreen.write(screen, into: &buf)
            
        
        case let .updateScreenStack(stack):
            writeInt(&buf, Int32(9))
            FfiConverterSequenceTypeScreen.write(stack, into: &buf)
            
        
        case let .createChat(peerNpub):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(peerNpub, into: &buf)
            
        
        case let .sendMessage(chatId,content):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(chatId, into: &buf)
            FfiConverterString.write(content, into: &buf)
            
        
        case let .retryMessage(chatId,messageId):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(chatId, into: &buf)
            FfiConverterString.write(messageId, into: &buf)
            
        
        case let .openChat(chatId):
            writeInt(&buf, Int32(13))
            FfiConverterString.write(chatId, into: &buf)
            
        
        case let .loadOlderMessages(chatId,beforeMessageId,limit):
            writeInt(&buf, Int32(14))
            FfiConverterString.write(chatId, into: &buf)
            FfiConverterString.write(beforeMessageId, into: &buf)
            FfiConverterUInt32.write(limit, into: &buf)
            
        
        case let .createGroupChat(peerNpubs,groupName):
            writeInt(&buf, Int32(15))
            FfiConverterSequenceString.write(peerNpubs, into: &buf)
            FfiConverterString.write(groupName, into: &buf)
            
        
        case let .addGroupMembers(chatId,peerNpubs):
            writeInt(&buf, Int32(16))
            FfiConverterString.write(chatId, into: &buf)
            FfiConverterSequenceString.write(peerNpubs, into: &buf)
            
        
        case let .removeGroupMembers(chatId,memberPubkeys):
            writeInt(&buf, Int32(17))
            FfiConverterString.write(chatId, into: &buf)
            FfiConverterSequenceString.write(memberPubkeys, into: &buf)
            
        
        case let .leaveGroup(chatId):
            writeInt(&buf, Int32(18))
            FfiConverterString.write(chatId, into: &buf)
            
        
        case let .renameGroup(chatId,name):
            writeInt(&buf, Int32(19))
            FfiConverterString.write(chatId, into: &buf)
            FfiConverterString.write(name, into: &buf)
            
        
        case let .archiveChat(chatId):
            writeInt(&buf, Int32(20))
            FfiConverterString.write(chatId, into: &buf)
            
        
        case .clearToast:
            writeInt(&buf, Int32(21))
        
        
        case .foregrounded:
            writeInt(&buf, Int32(22))
        
        
        case let .openPeerProfile(pubkey):
            writeInt(&buf, Int32(23))
            FfiConverterString.write(pubkey, into: &buf)
            
        
        case .closePeerProfile:
            writeInt(&buf, Int32(24))
        
        
        case .refreshFollowList:
            writeInt(&buf, Int32(25))
        
        
        case let .followUser(pubkey):
            writeInt(&buf, Int32(26))
            FfiConverterString.write(pubkey, into: &buf)
            
        
        case let .unfollowUser(pubkey):
            writeInt(&buf, Int32(27))
            FfiConverterString.write(pubkey, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppAction_lift(_ buf: RustBuffer) throws -> AppAction {
    return try FfiConverterTypeAppAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppAction_lower(_ value: AppAction) -> RustBuffer {
    return FfiConverterTypeAppAction.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AppUpdate: Equatable, Hashable {
    
    /**
     * Primary update stream: always send a full state snapshot.
     *
     * MVP tradeoff: simplest reconciliation story on iOS/Android; can be made more granular later.
     */
    case fullState(AppState
    )
    case accountCreated(rev: UInt64, nsec: String, pubkey: String, npub: String
    )





}

#if compiler(>=6)
extension AppUpdate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppUpdate: FfiConverterRustBuffer {
    typealias SwiftType = AppUpdate

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppUpdate {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .fullState(try FfiConverterTypeAppState.read(from: &buf)
        )
        
        case 2: return .accountCreated(rev: try FfiConverterUInt64.read(from: &buf), nsec: try FfiConverterString.read(from: &buf), pubkey: try FfiConverterString.read(from: &buf), npub: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AppUpdate, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .fullState(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeAppState.write(v1, into: &buf)
            
        
        case let .accountCreated(rev,nsec,pubkey,npub):
            writeInt(&buf, Int32(2))
            FfiConverterUInt64.write(rev, into: &buf)
            FfiConverterString.write(nsec, into: &buf)
            FfiConverterString.write(pubkey, into: &buf)
            FfiConverterString.write(npub, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppUpdate_lift(_ buf: RustBuffer) throws -> AppUpdate {
    return try FfiConverterTypeAppUpdate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppUpdate_lower(_ value: AppUpdate) -> RustBuffer {
    return FfiConverterTypeAppUpdate.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AuthState: Equatable, Hashable {
    
    case loggedOut
    case loggedIn(npub: String, pubkey: String
    )





}

#if compiler(>=6)
extension AuthState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthState: FfiConverterRustBuffer {
    typealias SwiftType = AuthState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .loggedOut
        
        case 2: return .loggedIn(npub: try FfiConverterString.read(from: &buf), pubkey: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AuthState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .loggedOut:
            writeInt(&buf, Int32(1))
        
        
        case let .loggedIn(npub,pubkey):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(npub, into: &buf)
            FfiConverterString.write(pubkey, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthState_lift(_ buf: RustBuffer) throws -> AuthState {
    return try FfiConverterTypeAuthState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthState_lower(_ value: AuthState) -> RustBuffer {
    return FfiConverterTypeAuthState.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MessageDeliveryState: Equatable, Hashable {
    
    case pending
    case sent
    case failed(reason: String
    )





}

#if compiler(>=6)
extension MessageDeliveryState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessageDeliveryState: FfiConverterRustBuffer {
    typealias SwiftType = MessageDeliveryState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessageDeliveryState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pending
        
        case 2: return .sent
        
        case 3: return .failed(reason: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MessageDeliveryState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .pending:
            writeInt(&buf, Int32(1))
        
        
        case .sent:
            writeInt(&buf, Int32(2))
        
        
        case let .failed(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageDeliveryState_lift(_ buf: RustBuffer) throws -> MessageDeliveryState {
    return try FfiConverterTypeMessageDeliveryState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageDeliveryState_lower(_ value: MessageDeliveryState) -> RustBuffer {
    return FfiConverterTypeMessageDeliveryState.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Screen: Equatable, Hashable {
    
    case login
    case chatList
    case chat(chatId: String
    )
    case newChat
    case newGroupChat
    case groupInfo(chatId: String
    )





}

#if compiler(>=6)
extension Screen: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScreen: FfiConverterRustBuffer {
    typealias SwiftType = Screen

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Screen {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .login
        
        case 2: return .chatList
        
        case 3: return .chat(chatId: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .newChat
        
        case 5: return .newGroupChat
        
        case 6: return .groupInfo(chatId: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Screen, into buf: inout [UInt8]) {
        switch value {
        
        
        case .login:
            writeInt(&buf, Int32(1))
        
        
        case .chatList:
            writeInt(&buf, Int32(2))
        
        
        case let .chat(chatId):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(chatId, into: &buf)
            
        
        case .newChat:
            writeInt(&buf, Int32(4))
        
        
        case .newGroupChat:
            writeInt(&buf, Int32(5))
        
        
        case let .groupInfo(chatId):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(chatId, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScreen_lift(_ buf: RustBuffer) throws -> Screen {
    return try FfiConverterTypeScreen.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScreen_lower(_ value: Screen) -> RustBuffer {
    return FfiConverterTypeScreen.lower(value)
}





public protocol AppReconciler: AnyObject, Sendable {
    
    func reconcile(update: AppUpdate) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceAppReconciler {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceAppReconciler] = [UniffiVTableCallbackInterfaceAppReconciler(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceAppReconciler.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface AppReconciler: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceAppReconciler.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface AppReconciler: handle missing in uniffiClone")
            }
        },
        reconcile: { (
            uniffiHandle: UInt64,
            update: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAppReconciler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.reconcile(
                     update: try FfiConverterTypeAppUpdate_lift(update)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitAppReconciler() {
    uniffi_pika_core_fn_init_callback_vtable_appreconciler(UniffiCallbackInterfaceAppReconciler.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceAppReconciler {
    fileprivate static let handleMap = UniffiHandleMap<AppReconciler>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceAppReconciler : FfiConverter {
    typealias SwiftType = AppReconciler
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAppReconciler_lift(_ handle: UInt64) throws -> AppReconciler {
    return try FfiConverterCallbackInterfaceAppReconciler.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAppReconciler_lower(_ v: AppReconciler) -> UInt64 {
    return FfiConverterCallbackInterfaceAppReconciler.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeChatViewState: FfiConverterRustBuffer {
    typealias SwiftType = ChatViewState?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeChatViewState.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeChatViewState.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePeerProfileState: FfiConverterRustBuffer {
    typealias SwiftType = PeerProfileState?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePeerProfileState.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePeerProfileState.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeChatMessage: FfiConverterRustBuffer {
    typealias SwiftType = [ChatMessage]

    public static func write(_ value: [ChatMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChatMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ChatMessage] {
        let len: Int32 = try readInt(&buf)
        var seq = [ChatMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeChatMessage.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeChatSummary: FfiConverterRustBuffer {
    typealias SwiftType = [ChatSummary]

    public static func write(_ value: [ChatSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChatSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ChatSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [ChatSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeChatSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFollowListEntry: FfiConverterRustBuffer {
    typealias SwiftType = [FollowListEntry]

    public static func write(_ value: [FollowListEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFollowListEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FollowListEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [FollowListEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFollowListEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMemberInfo: FfiConverterRustBuffer {
    typealias SwiftType = [MemberInfo]

    public static func write(_ value: [MemberInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMemberInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MemberInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [MemberInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMemberInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMention: FfiConverterRustBuffer {
    typealias SwiftType = [Mention]

    public static func write(_ value: [Mention], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMention.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Mention] {
        let len: Int32 = try readInt(&buf)
        var seq = [Mention]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMention.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePollTally: FfiConverterRustBuffer {
    typealias SwiftType = [PollTally]

    public static func write(_ value: [PollTally], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePollTally.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PollTally] {
        let len: Int32 = try readInt(&buf)
        var seq = [PollTally]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePollTally.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeScreen: FfiConverterRustBuffer {
    typealias SwiftType = [Screen]

    public static func write(_ value: [Screen], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeScreen.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Screen] {
        let len: Int32 = try readInt(&buf)
        var seq = [Screen]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeScreen.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pika_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pika_core_checksum_method_ffiapp_dispatch() != 60985) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pika_core_checksum_method_ffiapp_listen_for_updates() != 54024) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pika_core_checksum_method_ffiapp_state() != 64637) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pika_core_checksum_constructor_ffiapp_new() != 18606) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pika_core_checksum_method_appreconciler_reconcile() != 10811) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitAppReconciler()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePikaCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all