// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_APP_RECONCILER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_APP_RECONCILER_METHOD0
typedef void (*UniffiCallbackInterfaceAppReconcilerMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD0
typedef void (*UniffiCallbackInterfaceExternalSignerBridgeMethod0)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD1
typedef void (*UniffiCallbackInterfaceExternalSignerBridgeMethod1)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD2
typedef void (*UniffiCallbackInterfaceExternalSignerBridgeMethod2)(uint64_t, RustBuffer, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD3
typedef void (*UniffiCallbackInterfaceExternalSignerBridgeMethod3)(uint64_t, RustBuffer, RustBuffer, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD4
typedef void (*UniffiCallbackInterfaceExternalSignerBridgeMethod4)(uint64_t, RustBuffer, RustBuffer, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD5
typedef void (*UniffiCallbackInterfaceExternalSignerBridgeMethod5)(uint64_t, RustBuffer, RustBuffer, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE_METHOD6
typedef void (*UniffiCallbackInterfaceExternalSignerBridgeMethod6)(uint64_t, RustBuffer, RustBuffer, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_APP_RECONCILER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_APP_RECONCILER
typedef struct UniffiVTableCallbackInterfaceAppReconciler {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceAppReconcilerMethod0 _Nonnull reconcile;
} UniffiVTableCallbackInterfaceAppReconciler;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EXTERNAL_SIGNER_BRIDGE
typedef struct UniffiVTableCallbackInterfaceExternalSignerBridge {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceExternalSignerBridgeMethod0 _Nonnull openUrl;
    UniffiCallbackInterfaceExternalSignerBridgeMethod1 _Nonnull requestPublicKey;
    UniffiCallbackInterfaceExternalSignerBridgeMethod2 _Nonnull signEvent;
    UniffiCallbackInterfaceExternalSignerBridgeMethod3 _Nonnull nip44Encrypt;
    UniffiCallbackInterfaceExternalSignerBridgeMethod4 _Nonnull nip44Decrypt;
    UniffiCallbackInterfaceExternalSignerBridgeMethod5 _Nonnull nip04Encrypt;
    UniffiCallbackInterfaceExternalSignerBridgeMethod6 _Nonnull nip04Decrypt;
} UniffiVTableCallbackInterfaceExternalSignerBridge;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_CLONE_FFIAPP
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_CLONE_FFIAPP
uint64_t uniffi_pika_core_fn_clone_ffiapp(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_FREE_FFIAPP
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_FREE_FFIAPP
void uniffi_pika_core_fn_free_ffiapp(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_CONSTRUCTOR_FFIAPP_NEW
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_CONSTRUCTOR_FFIAPP_NEW
uint64_t uniffi_pika_core_fn_constructor_ffiapp_new(RustBuffer data_dir, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_METHOD_FFIAPP_DISPATCH
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_METHOD_FFIAPP_DISPATCH
void uniffi_pika_core_fn_method_ffiapp_dispatch(uint64_t ptr, RustBuffer action, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_METHOD_FFIAPP_LISTEN_FOR_UPDATES
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_METHOD_FFIAPP_LISTEN_FOR_UPDATES
void uniffi_pika_core_fn_method_ffiapp_listen_for_updates(uint64_t ptr, uint64_t reconciler, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_METHOD_FFIAPP_SET_EXTERNAL_SIGNER_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_METHOD_FFIAPP_SET_EXTERNAL_SIGNER_BRIDGE
void uniffi_pika_core_fn_method_ffiapp_set_external_signer_bridge(uint64_t ptr, uint64_t bridge, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_METHOD_FFIAPP_STATE
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_METHOD_FFIAPP_STATE
RustBuffer uniffi_pika_core_fn_method_ffiapp_state(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_INIT_CALLBACK_VTABLE_APPRECONCILER
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_INIT_CALLBACK_VTABLE_APPRECONCILER
void uniffi_pika_core_fn_init_callback_vtable_appreconciler(const UniffiVTableCallbackInterfaceAppReconciler* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_INIT_CALLBACK_VTABLE_EXTERNALSIGNERBRIDGE
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_FN_INIT_CALLBACK_VTABLE_EXTERNALSIGNERBRIDGE
void uniffi_pika_core_fn_init_callback_vtable_externalsignerbridge(const UniffiVTableCallbackInterfaceExternalSignerBridge* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUSTBUFFER_ALLOC
RustBuffer ffi_pika_core_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_pika_core_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUSTBUFFER_FREE
void ffi_pika_core_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUSTBUFFER_RESERVE
RustBuffer ffi_pika_core_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_U8
void ffi_pika_core_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_U8
void ffi_pika_core_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_U8
void ffi_pika_core_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_pika_core_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_I8
void ffi_pika_core_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_I8
void ffi_pika_core_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_I8
void ffi_pika_core_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_pika_core_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_U16
void ffi_pika_core_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_U16
void ffi_pika_core_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_U16
void ffi_pika_core_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_pika_core_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_I16
void ffi_pika_core_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_I16
void ffi_pika_core_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_I16
void ffi_pika_core_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_pika_core_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_U32
void ffi_pika_core_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_U32
void ffi_pika_core_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_U32
void ffi_pika_core_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_pika_core_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_I32
void ffi_pika_core_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_I32
void ffi_pika_core_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_I32
void ffi_pika_core_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_pika_core_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_U64
void ffi_pika_core_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_U64
void ffi_pika_core_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_U64
void ffi_pika_core_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_pika_core_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_I64
void ffi_pika_core_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_I64
void ffi_pika_core_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_I64
void ffi_pika_core_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_pika_core_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_F32
void ffi_pika_core_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_F32
void ffi_pika_core_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_F32
void ffi_pika_core_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_F32
float ffi_pika_core_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_F64
void ffi_pika_core_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_F64
void ffi_pika_core_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_F64
void ffi_pika_core_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_F64
double ffi_pika_core_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_pika_core_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_pika_core_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_pika_core_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_pika_core_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_POLL_VOID
void ffi_pika_core_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_CANCEL_VOID
void ffi_pika_core_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_FREE_VOID
void ffi_pika_core_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_RUST_FUTURE_COMPLETE_VOID
void ffi_pika_core_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_FFIAPP_DISPATCH
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_FFIAPP_DISPATCH
uint16_t uniffi_pika_core_checksum_method_ffiapp_dispatch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_FFIAPP_LISTEN_FOR_UPDATES
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_FFIAPP_LISTEN_FOR_UPDATES
uint16_t uniffi_pika_core_checksum_method_ffiapp_listen_for_updates(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_FFIAPP_SET_EXTERNAL_SIGNER_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_FFIAPP_SET_EXTERNAL_SIGNER_BRIDGE
uint16_t uniffi_pika_core_checksum_method_ffiapp_set_external_signer_bridge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_FFIAPP_STATE
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_FFIAPP_STATE
uint16_t uniffi_pika_core_checksum_method_ffiapp_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_CONSTRUCTOR_FFIAPP_NEW
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_CONSTRUCTOR_FFIAPP_NEW
uint16_t uniffi_pika_core_checksum_constructor_ffiapp_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_APPRECONCILER_RECONCILE
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_APPRECONCILER_RECONCILE
uint16_t uniffi_pika_core_checksum_method_appreconciler_reconcile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_OPEN_URL
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_OPEN_URL
uint16_t uniffi_pika_core_checksum_method_externalsignerbridge_open_url(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_REQUEST_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_REQUEST_PUBLIC_KEY
uint16_t uniffi_pika_core_checksum_method_externalsignerbridge_request_public_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_SIGN_EVENT
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_SIGN_EVENT
uint16_t uniffi_pika_core_checksum_method_externalsignerbridge_sign_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_NIP44_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_NIP44_ENCRYPT
uint16_t uniffi_pika_core_checksum_method_externalsignerbridge_nip44_encrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_NIP44_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_NIP44_DECRYPT
uint16_t uniffi_pika_core_checksum_method_externalsignerbridge_nip44_decrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_NIP04_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_NIP04_ENCRYPT
uint16_t uniffi_pika_core_checksum_method_externalsignerbridge_nip04_encrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_NIP04_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_PIKA_CORE_CHECKSUM_METHOD_EXTERNALSIGNERBRIDGE_NIP04_DECRYPT
uint16_t uniffi_pika_core_checksum_method_externalsignerbridge_nip04_decrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PIKA_CORE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_PIKA_CORE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_pika_core_uniffi_contract_version(void
    
);
#endif

