name: Pika
options:
  bundleIdPrefix: com.justinmoon
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

settings:
  base:
    # Note: device builds still need a valid DEVELOPMENT_TEAM; we keep that out of git and
    # pass it via env from tools/run-ios.
    PRODUCT_BUNDLE_IDENTIFIER: com.justinmoon.pika
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0
  configs:
    Debug:
      PRODUCT_BUNDLE_IDENTIFIER: com.justinmoon.pika.dev

packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"

targets:
  Pika:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Bindings
        excludes:
          - "*.h"
          - "*.modulemap"
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - framework: Frameworks/PikaCore.xcframework
        embed: false
      - package: MarkdownUI

  PikaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Pika

  PikaUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: Pika

schemes:
  Pika:
    build:
      targets:
        Pika: all
    test:
      targets:
        - name: PikaTests
          randomExecutionOrder: true
        - name: PikaUITests
          randomExecutionOrder: true
