name: Pika
options:
  bundleIdPrefix: com.justinmoon
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

settings:
  base:
    # Note: device builds still need a valid DEVELOPMENT_TEAM; we keep that out of git and
    # pass it via env from tools/run-ios.
    PRODUCT_BUNDLE_IDENTIFIER: com.justinmoon.pika
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0
  configs:
    Debug:
      PRODUCT_BUNDLE_IDENTIFIER: com.justinmoon.pika.dev

packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"

targets:
  Pika:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Bindings
        excludes:
          - "*.h"
          - "*.modulemap"
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
    dependencies:
      - framework: Frameworks/PikaCore.xcframework
        embed: false
      - package: MarkdownUI

  PikaTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - path: Tests
    dependencies:
      - target: Pika

  PikaUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - path: UITests
    postBuildScripts:
      - name: "Copy .env into test bundle"
        script: |
          ENV_SRC="${SRCROOT}/../.env"
          if [ ! -f "$ENV_SRC" ]; then
            echo "warning: .env not found at $ENV_SRC"
            exit 0
          fi

          # Device UI tests run the .xctest bundle inside the *Runner.app/PlugIns*.
          # Put env.test into the .xctest bundle so Bundle(for:) can find it.
          candidates=()
          if [ -n "${CODESIGNING_FOLDER_PATH:-}" ]; then candidates+=("$CODESIGNING_FOLDER_PATH"); fi
          if [ -n "${WRAPPER_NAME:-}" ]; then candidates+=("${TARGET_BUILD_DIR:-}/${WRAPPER_NAME}"); fi
          if [ -n "${WRAPPER_NAME:-}" ]; then candidates+=("${BUILT_PRODUCTS_DIR:-}/${WRAPPER_NAME}"); fi
          if [ -n "${XCTRUNNER_PRODUCT_NAME:-}" ] && [ -n "${WRAPPER_NAME:-}" ]; then
            candidates+=("${TARGET_BUILD_DIR:-}/${XCTRUNNER_PRODUCT_NAME}/PlugIns/${WRAPPER_NAME}")
            candidates+=("${BUILT_PRODUCTS_DIR:-}/${XCTRUNNER_PRODUCT_NAME}/PlugIns/${WRAPPER_NAME}")
          fi

          copied=0
          for dst in "${candidates[@]}"; do
            [ -n "$dst" ] || continue
            if [ -d "$dst" ]; then
              cp "$ENV_SRC" "$dst/env.test"
              echo "Copied .env to $dst/env.test"
              copied=1
              break
            fi
          done

          if [ "$copied" != "1" ]; then
            echo "warning: could not locate .xctest bundle; tried:"
            printf '  - %s\n' "${candidates[@]}"
          fi
        basedOnDependencyAnalysis: false
    dependencies:
      - target: Pika

schemes:
  Pika:
    build:
      targets:
        Pika: all
    test:
      targets:
        - name: PikaTests
          randomExecutionOrder: true
        - name: PikaUITests
          randomExecutionOrder: true
