name: Pika
options:
  bundleIdPrefix: org.pikachat
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

settings:
  base:
    # PIKA_APP_BUNDLE_ID is the "root" bundle id; targets derive from it.
    # Override on the xcodebuild command line (run-ios does this automatically).
    PIKA_APP_BUNDLE_ID: org.pikachat.pika
    PRODUCT_BUNDLE_IDENTIFIER: $(PIKA_APP_BUNDLE_ID)
    # Default callback URL scheme for non-run-ios builds (Xcode/archive). run-ios
    # overrides this per bundle id (pika, pika-dev, pika-test).
    PIKA_IOS_URL_SCHEME: pika
    # PIKA_APP_GROUP: derived from bundle ID. Override via xcodebuild if needed.
    PIKA_APP_GROUP: "group.$(PIKA_APP_BUNDLE_ID)"
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0

packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"

targets:
  Pika:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Bindings
        excludes:
          - "*.h"
          - "*.modulemap"
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        DEFINES_MODULE: YES
        ENABLE_TESTABILITY: YES
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        CODE_SIGN_ENTITLEMENTS: Pika.entitlements
    dependencies:
      - framework: Frameworks/PikaCore.xcframework
        embed: false
      - package: MarkdownUI
      - target: PikaNotificationService
    postBuildScripts:
      - name: "Stamp build number"
        script: |
          if [ -f "${PROJECT_DIR}/.build-number" ]; then
            BUILD_NUMBER=$(cat "${PROJECT_DIR}/.build-number")
          else
            BUILD_NUMBER=$(date +"%Y%m%d%H%M")
          fi
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}"
        basedOnDependencyAnalysis: false

  PikaNotificationService:
    type: app-extension
    platform: iOS
    sources:
      - path: NotificationService
      - path: NSEBindings
        excludes:
          - "*.h"
          - "*.modulemap"
    settings:
      base:
        PRODUCT_NAME: PikaNotificationService
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: NotificationService/Info.plist
        CODE_SIGN_ENTITLEMENTS: NotificationService/NotificationService.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: $(PIKA_APP_BUNDLE_ID).notification-service
    dependencies:
      - framework: Frameworks/PikaNSE.xcframework
        embed: false
    postBuildScripts:
      - name: "Stamp build number"
        script: |
          if [ -f "${PROJECT_DIR}/.build-number" ]; then
            BUILD_NUMBER=$(cat "${PROJECT_DIR}/.build-number")
          else
            BUILD_NUMBER=$(date +"%Y%m%d%H%M")
          fi
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}"
        basedOnDependencyAnalysis: false

  PikaTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_MODULE_NAME: "$(TARGET_NAME)"
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: Pika
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Pika.app/Pika"
        BUNDLE_LOADER: "$(TEST_HOST)"
    sources:
      - path: Tests
    dependencies:
      - target: Pika

  PikaUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_MODULE_NAME: "$(TARGET_NAME)"
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - path: UITests
    postBuildScripts:
      - name: "Copy .env into test bundle"
        script: |
          ENV_SRC="${SRCROOT}/../.env"
          if [ ! -f "$ENV_SRC" ]; then
            echo "warning: .env not found at $ENV_SRC"
            exit 0
          fi

          # Device UI tests run the .xctest bundle inside the *Runner.app/PlugIns*.
          # Put env.test into the .xctest bundle so Bundle(for:) can find it.
          candidates=()
          if [ -n "${CODESIGNING_FOLDER_PATH:-}" ]; then candidates+=("$CODESIGNING_FOLDER_PATH"); fi
          if [ -n "${WRAPPER_NAME:-}" ]; then candidates+=("${TARGET_BUILD_DIR:-}/${WRAPPER_NAME}"); fi
          if [ -n "${WRAPPER_NAME:-}" ]; then candidates+=("${BUILT_PRODUCTS_DIR:-}/${WRAPPER_NAME}"); fi
          if [ -n "${XCTRUNNER_PRODUCT_NAME:-}" ] && [ -n "${WRAPPER_NAME:-}" ]; then
            candidates+=("${TARGET_BUILD_DIR:-}/${XCTRUNNER_PRODUCT_NAME}/PlugIns/${WRAPPER_NAME}")
            candidates+=("${BUILT_PRODUCTS_DIR:-}/${XCTRUNNER_PRODUCT_NAME}/PlugIns/${WRAPPER_NAME}")
          fi

          copied=0
          for dst in "${candidates[@]}"; do
            [ -n "$dst" ] || continue
            if [ -d "$dst" ]; then
              cp "$ENV_SRC" "$dst/env.test"
              echo "Copied .env to $dst/env.test"
              copied=1
              break
            fi
          done

          if [ "$copied" != "1" ]; then
            echo "warning: could not locate .xctest bundle; tried:"
            printf '  - %s\n' "${candidates[@]}"
          fi
        basedOnDependencyAnalysis: false
    dependencies:
      - target: Pika

schemes:
  Pika:
    build:
      preActions:
        - script: 'date +"%Y%m%d%H%M" > "${PROJECT_DIR}/.build-number"'
          settingsTarget: Pika
      targets:
        Pika: all
    test:
      targets:
        - name: PikaTests
          randomExecutionOrder: true
        - name: PikaUITests
          randomExecutionOrder: true
